version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "build(root)"
      include: "scope"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/packages/web-components"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "build(root)"
      include: "scope"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "build(react)"
      include: "scope"
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/packages/fonts"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    commit-message:
      prefix: "build(fonts)"
      include: "scope"
    open-pull-requests-limit: 0