export const IC_SELECT = "ic-select";
export const IC_INPUT_CONTAINER = "ic-input-component-container";
export const IC_MENU_LI = "ic-menu ul li";
export const IC_MENU_UL = "ic-menu ul";
export const SC_IC_MENU_TYPOGRAPHY = ".sc-ic-menu ic-typography";
export const DISABLED_OPTION_MENU = "option disabled-option sc-ic-menu";
export const IC_TYPOGRAPHY = "ic-typography";
export const ID_CLEAR_BUTTON = "#clear-button";
export const ARIA_SELECTED = "aria-selected";

export const TYPE_DOWN_ARROW = "{downArrow}";
export const TYPE_ENTER = "{enter}";
export const TYPE_BACKSPACE = "{backspace}";
export const DATA_VALUE_ESPRESSO = "[data-value='espresso']";
export const DATA_VALUE_CAP = '[data-value="Cap"]';
export const DATA_VALUE_AMERICANO = '[data-value="americano"]';
export const DATA_LABEL_CAPPUCCINO = '[data-label="Cappuccino"]';
export const DATA_LABEL_ESPRESSO = '[data-label="Espresso"]';
export const INPUT_TYPE_HIDDEN = "input[type='hidden']";
export const NO_RESULTS_FOUND = "No results found";
export const RETRY_BUTTON = "#retry-button";
export const LOADING_MESSAGE = "Loading...";
