name: ✍️ Suggest an improvement to our processes
description: Suggest an improvement to our processes, ways of working or testing function.
labels: []
type: Process improvement
body:
  - type: markdown
    attributes:
      value: |
        Please use this form to suggest an improvement to our processes, ways of working or testing function.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Tell us, in a few words, what the improvement is.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a full description of what the improvement should be and how it should work.
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: If applicable, tell us how urgent it is that this issue gets resolved, based on the impact it has on your team's work or project timeline.
      multiple: true
      options:
        - N/A - Not time sensitive
        - Low - Does not have significant impact and can be addressed at a convenient time without causing delays.
        - Medium - Has moderate impact and should be addressed soon to avoid potential delays or complications.
        - High - A critical issue which has significant impact and needs immediate attention to prevent major delays or blockers.
    validations:
      required: false
  - type: textarea
    id: why
    attributes:
      label: Why do we need it?
      description: Let us know why we need to implement this
    validations:
      required: false