/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type IcButtonCustomEvent, type IcChangeEventDetail, type IcCheckboxGroupCustomEvent, type IcExpandedDetail, type IcItemsPerPageChangeEventDetail, type IcMenuChangeEventDetail, type IcMultiValueEventDetail, type IcOptionSelectEventDetail, type IcPageChangeEventDetail, type IcPaginationBarCustomEvent, type IcPaginationCustomEvent, type IcPopoverMenuCustomEvent, type IcRadioGroupCustomEvent, type IcRadioOptionCustomEvent, type IcSearchBarBlurEventDetail, type IcSearchBarCustomEvent, type IcSelectCustomEvent, type IcSideNavigationCustomEvent, type IcSwitchChangeEventDetail, type IcSwitchCustomEvent, type IcTabContextCustomEvent, type IcTabSelectEventDetail, type IcTextFieldCustomEvent, type IcTextFieldKeydownEventDetail, type IcThemeCustomEvent, type IcThemeSettings, type IcToggleButtonGroupCustomEvent, type IcValueEventDetail } from "@ukic/web-components";
import { IcAccordionGroup as IcAccordionGroupElement, defineCustomElement as defineIcAccordionGroup } from "@ukic/web-components/dist/components/ic-accordion-group.js";
import { IcAccordion as IcAccordionElement, defineCustomElement as defineIcAccordion } from "@ukic/web-components/dist/components/ic-accordion.js";
import { IcActionChip as IcActionChipElement, defineCustomElement as defineIcActionChip } from "@ukic/web-components/dist/components/ic-action-chip.js";
import { IcAlert as IcAlertElement, defineCustomElement as defineIcAlert } from "@ukic/web-components/dist/components/ic-alert.js";
import { IcBackToTop as IcBackToTopElement, defineCustomElement as defineIcBackToTop } from "@ukic/web-components/dist/components/ic-back-to-top.js";
import { IcBadge as IcBadgeElement, defineCustomElement as defineIcBadge } from "@ukic/web-components/dist/components/ic-badge.js";
import { IcBreadcrumbGroup as IcBreadcrumbGroupElement, defineCustomElement as defineIcBreadcrumbGroup } from "@ukic/web-components/dist/components/ic-breadcrumb-group.js";
import { IcBreadcrumb as IcBreadcrumbElement, defineCustomElement as defineIcBreadcrumb } from "@ukic/web-components/dist/components/ic-breadcrumb.js";
import { IcButton as IcButtonElement, defineCustomElement as defineIcButton } from "@ukic/web-components/dist/components/ic-button.js";
import { IcCardHorizontal as IcCardHorizontalElement, defineCustomElement as defineIcCardHorizontal } from "@ukic/web-components/dist/components/ic-card-horizontal.js";
import { IcCardVertical as IcCardVerticalElement, defineCustomElement as defineIcCardVertical } from "@ukic/web-components/dist/components/ic-card-vertical.js";
import { IcCheckboxGroup as IcCheckboxGroupElement, defineCustomElement as defineIcCheckboxGroup } from "@ukic/web-components/dist/components/ic-checkbox-group.js";
import { IcCheckbox as IcCheckboxElement, defineCustomElement as defineIcCheckbox } from "@ukic/web-components/dist/components/ic-checkbox.js";
import { IcChip as IcChipElement, defineCustomElement as defineIcChip } from "@ukic/web-components/dist/components/ic-chip.js";
import { IcClassificationBanner as IcClassificationBannerElement, defineCustomElement as defineIcClassificationBanner } from "@ukic/web-components/dist/components/ic-classification-banner.js";
import { IcDataList as IcDataListElement, defineCustomElement as defineIcDataList } from "@ukic/web-components/dist/components/ic-data-list.js";
import { IcDataRow as IcDataRowElement, defineCustomElement as defineIcDataRow } from "@ukic/web-components/dist/components/ic-data-row.js";
import { IcDialog as IcDialogElement, defineCustomElement as defineIcDialog } from "@ukic/web-components/dist/components/ic-dialog.js";
import { IcDivider as IcDividerElement, defineCustomElement as defineIcDivider } from "@ukic/web-components/dist/components/ic-divider.js";
import { IcEmptyState as IcEmptyStateElement, defineCustomElement as defineIcEmptyState } from "@ukic/web-components/dist/components/ic-empty-state.js";
import { IcFooterLinkGroup as IcFooterLinkGroupElement, defineCustomElement as defineIcFooterLinkGroup } from "@ukic/web-components/dist/components/ic-footer-link-group.js";
import { IcFooterLink as IcFooterLinkElement, defineCustomElement as defineIcFooterLink } from "@ukic/web-components/dist/components/ic-footer-link.js";
import { IcFooter as IcFooterElement, defineCustomElement as defineIcFooter } from "@ukic/web-components/dist/components/ic-footer.js";
import { IcHero as IcHeroElement, defineCustomElement as defineIcHero } from "@ukic/web-components/dist/components/ic-hero.js";
import { IcHorizontalScroll as IcHorizontalScrollElement, defineCustomElement as defineIcHorizontalScroll } from "@ukic/web-components/dist/components/ic-horizontal-scroll.js";
import { IcInputComponentContainer as IcInputComponentContainerElement, defineCustomElement as defineIcInputComponentContainer } from "@ukic/web-components/dist/components/ic-input-component-container.js";
import { IcInputContainer as IcInputContainerElement, defineCustomElement as defineIcInputContainer } from "@ukic/web-components/dist/components/ic-input-container.js";
import { IcInputLabel as IcInputLabelElement, defineCustomElement as defineIcInputLabel } from "@ukic/web-components/dist/components/ic-input-label.js";
import { IcInputValidation as IcInputValidationElement, defineCustomElement as defineIcInputValidation } from "@ukic/web-components/dist/components/ic-input-validation.js";
import { IcLayoutGridItem as IcLayoutGridItemElement, defineCustomElement as defineIcLayoutGridItem } from "@ukic/web-components/dist/components/ic-layout-grid-item.js";
import { IcLayoutGrid as IcLayoutGridElement, defineCustomElement as defineIcLayoutGrid } from "@ukic/web-components/dist/components/ic-layout-grid.js";
import { IcLink as IcLinkElement, defineCustomElement as defineIcLink } from "@ukic/web-components/dist/components/ic-link.js";
import { IcLoadingIndicator as IcLoadingIndicatorElement, defineCustomElement as defineIcLoadingIndicator } from "@ukic/web-components/dist/components/ic-loading-indicator.js";
import { IcMenuGroup as IcMenuGroupElement, defineCustomElement as defineIcMenuGroup } from "@ukic/web-components/dist/components/ic-menu-group.js";
import { IcMenuItem as IcMenuItemElement, defineCustomElement as defineIcMenuItem } from "@ukic/web-components/dist/components/ic-menu-item.js";
import { IcMenu as IcMenuElement, defineCustomElement as defineIcMenu } from "@ukic/web-components/dist/components/ic-menu.js";
import { IcNavigationButton as IcNavigationButtonElement, defineCustomElement as defineIcNavigationButton } from "@ukic/web-components/dist/components/ic-navigation-button.js";
import { IcNavigationGroup as IcNavigationGroupElement, defineCustomElement as defineIcNavigationGroup } from "@ukic/web-components/dist/components/ic-navigation-group.js";
import { IcNavigationItem as IcNavigationItemElement, defineCustomElement as defineIcNavigationItem } from "@ukic/web-components/dist/components/ic-navigation-item.js";
import { IcNavigationMenu as IcNavigationMenuElement, defineCustomElement as defineIcNavigationMenu } from "@ukic/web-components/dist/components/ic-navigation-menu.js";
import { IcPageHeader as IcPageHeaderElement, defineCustomElement as defineIcPageHeader } from "@ukic/web-components/dist/components/ic-page-header.js";
import { IcPaginationBar as IcPaginationBarElement, defineCustomElement as defineIcPaginationBar } from "@ukic/web-components/dist/components/ic-pagination-bar.js";
import { IcPaginationItem as IcPaginationItemElement, defineCustomElement as defineIcPaginationItem } from "@ukic/web-components/dist/components/ic-pagination-item.js";
import { IcPagination as IcPaginationElement, defineCustomElement as defineIcPagination } from "@ukic/web-components/dist/components/ic-pagination.js";
import { IcPopoverMenu as IcPopoverMenuElement, defineCustomElement as defineIcPopoverMenu } from "@ukic/web-components/dist/components/ic-popover-menu.js";
import { IcRadioGroup as IcRadioGroupElement, defineCustomElement as defineIcRadioGroup } from "@ukic/web-components/dist/components/ic-radio-group.js";
import { IcRadioOption as IcRadioOptionElement, defineCustomElement as defineIcRadioOption } from "@ukic/web-components/dist/components/ic-radio-option.js";
import { IcSearchBar as IcSearchBarElement, defineCustomElement as defineIcSearchBar } from "@ukic/web-components/dist/components/ic-search-bar.js";
import { IcSectionContainer as IcSectionContainerElement, defineCustomElement as defineIcSectionContainer } from "@ukic/web-components/dist/components/ic-section-container.js";
import { IcSelect as IcSelectElement, defineCustomElement as defineIcSelect } from "@ukic/web-components/dist/components/ic-select.js";
import { IcSideNavigation as IcSideNavigationElement, defineCustomElement as defineIcSideNavigation } from "@ukic/web-components/dist/components/ic-side-navigation.js";
import { IcSkeleton as IcSkeletonElement, defineCustomElement as defineIcSkeleton } from "@ukic/web-components/dist/components/ic-skeleton.js";
import { IcSkipLink as IcSkipLinkElement, defineCustomElement as defineIcSkipLink } from "@ukic/web-components/dist/components/ic-skip-link.js";
import { IcStatusTag as IcStatusTagElement, defineCustomElement as defineIcStatusTag } from "@ukic/web-components/dist/components/ic-status-tag.js";
import { IcStep as IcStepElement, defineCustomElement as defineIcStep } from "@ukic/web-components/dist/components/ic-step.js";
import { IcStepper as IcStepperElement, defineCustomElement as defineIcStepper } from "@ukic/web-components/dist/components/ic-stepper.js";
import { IcSwitch as IcSwitchElement, defineCustomElement as defineIcSwitch } from "@ukic/web-components/dist/components/ic-switch.js";
import { IcTabContext as IcTabContextElement, defineCustomElement as defineIcTabContext } from "@ukic/web-components/dist/components/ic-tab-context.js";
import { IcTabGroup as IcTabGroupElement, defineCustomElement as defineIcTabGroup } from "@ukic/web-components/dist/components/ic-tab-group.js";
import { IcTabPanel as IcTabPanelElement, defineCustomElement as defineIcTabPanel } from "@ukic/web-components/dist/components/ic-tab-panel.js";
import { IcTab as IcTabElement, defineCustomElement as defineIcTab } from "@ukic/web-components/dist/components/ic-tab.js";
import { IcTextField as IcTextFieldElement, defineCustomElement as defineIcTextField } from "@ukic/web-components/dist/components/ic-text-field.js";
import { IcTheme as IcThemeElement, defineCustomElement as defineIcTheme } from "@ukic/web-components/dist/components/ic-theme.js";
import { IcToastRegion as IcToastRegionElement, defineCustomElement as defineIcToastRegion } from "@ukic/web-components/dist/components/ic-toast-region.js";
import { IcToast as IcToastElement, defineCustomElement as defineIcToast } from "@ukic/web-components/dist/components/ic-toast.js";
import { IcToggleButtonGroup as IcToggleButtonGroupElement, defineCustomElement as defineIcToggleButtonGroup } from "@ukic/web-components/dist/components/ic-toggle-button-group.js";
import { IcToggleButton as IcToggleButtonElement, defineCustomElement as defineIcToggleButton } from "@ukic/web-components/dist/components/ic-toggle-button.js";
import { IcTooltip as IcTooltipElement, defineCustomElement as defineIcTooltip } from "@ukic/web-components/dist/components/ic-tooltip.js";
import { IcTopNavigation as IcTopNavigationElement, defineCustomElement as defineIcTopNavigation } from "@ukic/web-components/dist/components/ic-top-navigation.js";
import { IcTypography as IcTypographyElement, defineCustomElement as defineIcTypography } from "@ukic/web-components/dist/components/ic-typography.js";
import React from 'react';

type IcAccordionEvents = NonNullable<unknown>;

export const IcAccordion = /*@__PURE__*/ createComponent<IcAccordionElement, IcAccordionEvents>({
    tagName: 'ic-accordion',
    elementClass: IcAccordionElement,
    react: React,
    events: {} as IcAccordionEvents,
    defineCustomElement: defineIcAccordion
});

type IcAccordionGroupEvents = NonNullable<unknown>;

export const IcAccordionGroup = /*@__PURE__*/ createComponent<IcAccordionGroupElement, IcAccordionGroupEvents>({
    tagName: 'ic-accordion-group',
    elementClass: IcAccordionGroupElement,
    react: React,
    events: {} as IcAccordionGroupEvents,
    defineCustomElement: defineIcAccordionGroup
});

type IcActionChipEvents = NonNullable<unknown>;

export const IcActionChip = /*@__PURE__*/ createComponent<IcActionChipElement, IcActionChipEvents>({
    tagName: 'ic-action-chip',
    elementClass: IcActionChipElement,
    react: React,
    events: {} as IcActionChipEvents,
    defineCustomElement: defineIcActionChip
});

type IcAlertEvents = { onIcDismiss: EventName<CustomEvent<void>> };

export const IcAlert = /*@__PURE__*/ createComponent<IcAlertElement, IcAlertEvents>({
    tagName: 'ic-alert',
    elementClass: IcAlertElement,
    react: React,
    events: { onIcDismiss: 'icDismiss' } as IcAlertEvents,
    defineCustomElement: defineIcAlert
});

type IcBackToTopEvents = NonNullable<unknown>;

export const IcBackToTop = /*@__PURE__*/ createComponent<IcBackToTopElement, IcBackToTopEvents>({
    tagName: 'ic-back-to-top',
    elementClass: IcBackToTopElement,
    react: React,
    events: {} as IcBackToTopEvents,
    defineCustomElement: defineIcBackToTop
});

type IcBadgeEvents = NonNullable<unknown>;

export const IcBadge = /*@__PURE__*/ createComponent<IcBadgeElement, IcBadgeEvents>({
    tagName: 'ic-badge',
    elementClass: IcBadgeElement,
    react: React,
    events: {} as IcBadgeEvents,
    defineCustomElement: defineIcBadge
});

type IcBreadcrumbEvents = NonNullable<unknown>;

export const IcBreadcrumb = /*@__PURE__*/ createComponent<IcBreadcrumbElement, IcBreadcrumbEvents>({
    tagName: 'ic-breadcrumb',
    elementClass: IcBreadcrumbElement,
    react: React,
    events: {} as IcBreadcrumbEvents,
    defineCustomElement: defineIcBreadcrumb
});

type IcBreadcrumbGroupEvents = NonNullable<unknown>;

export const IcBreadcrumbGroup = /*@__PURE__*/ createComponent<IcBreadcrumbGroupElement, IcBreadcrumbGroupEvents>({
    tagName: 'ic-breadcrumb-group',
    elementClass: IcBreadcrumbGroupElement,
    react: React,
    events: {} as IcBreadcrumbGroupEvents,
    defineCustomElement: defineIcBreadcrumbGroup
});

type IcButtonEvents = {
    onIcBlur: EventName<CustomEvent<void>>,
    onIcFileSelection: EventName<IcButtonCustomEvent<FileList>>,
    onIcFocus: EventName<CustomEvent<void>>
};

export const IcButton = /*@__PURE__*/ createComponent<IcButtonElement, IcButtonEvents>({
    tagName: 'ic-button',
    elementClass: IcButtonElement,
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcFileSelection: 'icFileSelection',
        onIcFocus: 'icFocus'
    } as IcButtonEvents,
    defineCustomElement: defineIcButton
});

type IcCardHorizontalEvents = NonNullable<unknown>;

export const IcCardHorizontal = /*@__PURE__*/ createComponent<IcCardHorizontalElement, IcCardHorizontalEvents>({
    tagName: 'ic-card-horizontal',
    elementClass: IcCardHorizontalElement,
    react: React,
    events: {} as IcCardHorizontalEvents,
    defineCustomElement: defineIcCardHorizontal
});

type IcCardVerticalEvents = NonNullable<unknown>;

export const IcCardVertical = /*@__PURE__*/ createComponent<IcCardVerticalElement, IcCardVerticalEvents>({
    tagName: 'ic-card-vertical',
    elementClass: IcCardVerticalElement,
    react: React,
    events: {} as IcCardVerticalEvents,
    defineCustomElement: defineIcCardVertical
});

type IcCheckboxEvents = { onIcCheck: EventName<CustomEvent<void>> };

export const IcCheckbox = /*@__PURE__*/ createComponent<IcCheckboxElement, IcCheckboxEvents>({
    tagName: 'ic-checkbox',
    elementClass: IcCheckboxElement,
    react: React,
    events: { onIcCheck: 'icCheck' } as IcCheckboxEvents,
    defineCustomElement: defineIcCheckbox
});

type IcCheckboxGroupEvents = { onIcChange: EventName<IcCheckboxGroupCustomEvent<IcChangeEventDetail>> };

export const IcCheckboxGroup = /*@__PURE__*/ createComponent<IcCheckboxGroupElement, IcCheckboxGroupEvents>({
    tagName: 'ic-checkbox-group',
    elementClass: IcCheckboxGroupElement,
    react: React,
    events: { onIcChange: 'icChange' } as IcCheckboxGroupEvents,
    defineCustomElement: defineIcCheckboxGroup
});

type IcChipEvents = { onIcDismiss: EventName<CustomEvent<void>> };

export const IcChip = /*@__PURE__*/ createComponent<IcChipElement, IcChipEvents>({
    tagName: 'ic-chip',
    elementClass: IcChipElement,
    react: React,
    events: { onIcDismiss: 'icDismiss' } as IcChipEvents,
    defineCustomElement: defineIcChip
});

type IcClassificationBannerEvents = NonNullable<unknown>;

export const IcClassificationBanner = /*@__PURE__*/ createComponent<IcClassificationBannerElement, IcClassificationBannerEvents>({
    tagName: 'ic-classification-banner',
    elementClass: IcClassificationBannerElement,
    react: React,
    events: {} as IcClassificationBannerEvents,
    defineCustomElement: defineIcClassificationBanner
});

type IcDataListEvents = NonNullable<unknown>;

export const IcDataList = /*@__PURE__*/ createComponent<IcDataListElement, IcDataListEvents>({
    tagName: 'ic-data-list',
    elementClass: IcDataListElement,
    react: React,
    events: {} as IcDataListEvents,
    defineCustomElement: defineIcDataList
});

type IcDataRowEvents = NonNullable<unknown>;

export const IcDataRow = /*@__PURE__*/ createComponent<IcDataRowElement, IcDataRowEvents>({
    tagName: 'ic-data-row',
    elementClass: IcDataRowElement,
    react: React,
    events: {} as IcDataRowEvents,
    defineCustomElement: defineIcDataRow
});

type IcDialogEvents = {
    onIcDialogCancelled: EventName<CustomEvent<void>>,
    onIcDialogClosed: EventName<CustomEvent<void>>,
    onIcDialogConfirmed: EventName<CustomEvent<void>>,
    onIcDialogOpened: EventName<CustomEvent<void>>
};

export const IcDialog = /*@__PURE__*/ createComponent<IcDialogElement, IcDialogEvents>({
    tagName: 'ic-dialog',
    elementClass: IcDialogElement,
    react: React,
    events: {
        onIcDialogCancelled: 'icDialogCancelled',
        onIcDialogClosed: 'icDialogClosed',
        onIcDialogConfirmed: 'icDialogConfirmed',
        onIcDialogOpened: 'icDialogOpened'
    } as IcDialogEvents,
    defineCustomElement: defineIcDialog
});

type IcDividerEvents = NonNullable<unknown>;

export const IcDivider = /*@__PURE__*/ createComponent<IcDividerElement, IcDividerEvents>({
    tagName: 'ic-divider',
    elementClass: IcDividerElement,
    react: React,
    events: {} as IcDividerEvents,
    defineCustomElement: defineIcDivider
});

type IcEmptyStateEvents = NonNullable<unknown>;

export const IcEmptyState = /*@__PURE__*/ createComponent<IcEmptyStateElement, IcEmptyStateEvents>({
    tagName: 'ic-empty-state',
    elementClass: IcEmptyStateElement,
    react: React,
    events: {} as IcEmptyStateEvents,
    defineCustomElement: defineIcEmptyState
});

type IcFooterEvents = NonNullable<unknown>;

export const IcFooter = /*@__PURE__*/ createComponent<IcFooterElement, IcFooterEvents>({
    tagName: 'ic-footer',
    elementClass: IcFooterElement,
    react: React,
    events: {} as IcFooterEvents,
    defineCustomElement: defineIcFooter
});

type IcFooterLinkEvents = NonNullable<unknown>;

export const IcFooterLink = /*@__PURE__*/ createComponent<IcFooterLinkElement, IcFooterLinkEvents>({
    tagName: 'ic-footer-link',
    elementClass: IcFooterLinkElement,
    react: React,
    events: {} as IcFooterLinkEvents,
    defineCustomElement: defineIcFooterLink
});

type IcFooterLinkGroupEvents = NonNullable<unknown>;

export const IcFooterLinkGroup = /*@__PURE__*/ createComponent<IcFooterLinkGroupElement, IcFooterLinkGroupEvents>({
    tagName: 'ic-footer-link-group',
    elementClass: IcFooterLinkGroupElement,
    react: React,
    events: {} as IcFooterLinkGroupEvents,
    defineCustomElement: defineIcFooterLinkGroup
});

type IcHeroEvents = NonNullable<unknown>;

export const IcHero = /*@__PURE__*/ createComponent<IcHeroElement, IcHeroEvents>({
    tagName: 'ic-hero',
    elementClass: IcHeroElement,
    react: React,
    events: {} as IcHeroEvents,
    defineCustomElement: defineIcHero
});

type IcHorizontalScrollEvents = NonNullable<unknown>;

export const IcHorizontalScroll = /*@__PURE__*/ createComponent<IcHorizontalScrollElement, IcHorizontalScrollEvents>({
    tagName: 'ic-horizontal-scroll',
    elementClass: IcHorizontalScrollElement,
    react: React,
    events: {} as IcHorizontalScrollEvents,
    defineCustomElement: defineIcHorizontalScroll
});

type IcInputComponentContainerEvents = NonNullable<unknown>;

export const IcInputComponentContainer = /*@__PURE__*/ createComponent<IcInputComponentContainerElement, IcInputComponentContainerEvents>({
    tagName: 'ic-input-component-container',
    elementClass: IcInputComponentContainerElement,
    react: React,
    events: {} as IcInputComponentContainerEvents,
    defineCustomElement: defineIcInputComponentContainer
});

type IcInputContainerEvents = NonNullable<unknown>;

export const IcInputContainer = /*@__PURE__*/ createComponent<IcInputContainerElement, IcInputContainerEvents>({
    tagName: 'ic-input-container',
    elementClass: IcInputContainerElement,
    react: React,
    events: {} as IcInputContainerEvents,
    defineCustomElement: defineIcInputContainer
});

type IcInputLabelEvents = NonNullable<unknown>;

export const IcInputLabel = /*@__PURE__*/ createComponent<IcInputLabelElement, IcInputLabelEvents>({
    tagName: 'ic-input-label',
    elementClass: IcInputLabelElement,
    react: React,
    events: {} as IcInputLabelEvents,
    defineCustomElement: defineIcInputLabel
});

type IcInputValidationEvents = NonNullable<unknown>;

export const IcInputValidation = /*@__PURE__*/ createComponent<IcInputValidationElement, IcInputValidationEvents>({
    tagName: 'ic-input-validation',
    elementClass: IcInputValidationElement,
    react: React,
    events: {} as IcInputValidationEvents,
    defineCustomElement: defineIcInputValidation
});

type IcLayoutGridEvents = NonNullable<unknown>;

export const IcLayoutGrid = /*@__PURE__*/ createComponent<IcLayoutGridElement, IcLayoutGridEvents>({
    tagName: 'ic-layout-grid',
    elementClass: IcLayoutGridElement,
    react: React,
    events: {} as IcLayoutGridEvents,
    defineCustomElement: defineIcLayoutGrid
});

type IcLayoutGridItemEvents = NonNullable<unknown>;

export const IcLayoutGridItem = /*@__PURE__*/ createComponent<IcLayoutGridItemElement, IcLayoutGridItemEvents>({
    tagName: 'ic-layout-grid-item',
    elementClass: IcLayoutGridItemElement,
    react: React,
    events: {} as IcLayoutGridItemEvents,
    defineCustomElement: defineIcLayoutGridItem
});

type IcLinkEvents = NonNullable<unknown>;

export const IcLink = /*@__PURE__*/ createComponent<IcLinkElement, IcLinkEvents>({
    tagName: 'ic-link',
    elementClass: IcLinkElement,
    react: React,
    events: {} as IcLinkEvents,
    defineCustomElement: defineIcLink
});

type IcLoadingIndicatorEvents = NonNullable<unknown>;

export const IcLoadingIndicator = /*@__PURE__*/ createComponent<IcLoadingIndicatorElement, IcLoadingIndicatorEvents>({
    tagName: 'ic-loading-indicator',
    elementClass: IcLoadingIndicatorElement,
    react: React,
    events: {} as IcLoadingIndicatorEvents,
    defineCustomElement: defineIcLoadingIndicator
});

type IcMenuEvents = { onIcClear: EventName<CustomEvent<void>> };

export const IcMenu = /*@__PURE__*/ createComponent<IcMenuElement, IcMenuEvents>({
    tagName: 'ic-menu',
    elementClass: IcMenuElement,
    react: React,
    events: { onIcClear: 'icClear' } as IcMenuEvents,
    defineCustomElement: defineIcMenu
});

type IcMenuGroupEvents = NonNullable<unknown>;

export const IcMenuGroup = /*@__PURE__*/ createComponent<IcMenuGroupElement, IcMenuGroupEvents>({
    tagName: 'ic-menu-group',
    elementClass: IcMenuGroupElement,
    react: React,
    events: {} as IcMenuGroupEvents,
    defineCustomElement: defineIcMenuGroup
});

type IcMenuItemEvents = {
    onIcToggleChecked: EventName<CustomEvent<{
        checked: boolean;
    }>>
};

export const IcMenuItem = /*@__PURE__*/ createComponent<IcMenuItemElement, IcMenuItemEvents>({
    tagName: 'ic-menu-item',
    elementClass: IcMenuItemElement,
    react: React,
    events: { onIcToggleChecked: 'icToggleChecked' } as IcMenuItemEvents,
    defineCustomElement: defineIcMenuItem
});

type IcNavigationButtonEvents = NonNullable<unknown>;

export const IcNavigationButton = /*@__PURE__*/ createComponent<IcNavigationButtonElement, IcNavigationButtonEvents>({
    tagName: 'ic-navigation-button',
    elementClass: IcNavigationButtonElement,
    react: React,
    events: {} as IcNavigationButtonEvents,
    defineCustomElement: defineIcNavigationButton
});

type IcNavigationGroupEvents = NonNullable<unknown>;

export const IcNavigationGroup = /*@__PURE__*/ createComponent<IcNavigationGroupElement, IcNavigationGroupEvents>({
    tagName: 'ic-navigation-group',
    elementClass: IcNavigationGroupElement,
    react: React,
    events: {} as IcNavigationGroupEvents,
    defineCustomElement: defineIcNavigationGroup
});

type IcNavigationItemEvents = NonNullable<unknown>;

export const IcNavigationItem = /*@__PURE__*/ createComponent<IcNavigationItemElement, IcNavigationItemEvents>({
    tagName: 'ic-navigation-item',
    elementClass: IcNavigationItemElement,
    react: React,
    events: {} as IcNavigationItemEvents,
    defineCustomElement: defineIcNavigationItem
});

type IcNavigationMenuEvents = NonNullable<unknown>;

export const IcNavigationMenu = /*@__PURE__*/ createComponent<IcNavigationMenuElement, IcNavigationMenuEvents>({
    tagName: 'ic-navigation-menu',
    elementClass: IcNavigationMenuElement,
    react: React,
    events: {} as IcNavigationMenuEvents,
    defineCustomElement: defineIcNavigationMenu
});

type IcPageHeaderEvents = NonNullable<unknown>;

export const IcPageHeader = /*@__PURE__*/ createComponent<IcPageHeaderElement, IcPageHeaderEvents>({
    tagName: 'ic-page-header',
    elementClass: IcPageHeaderElement,
    react: React,
    events: {} as IcPageHeaderEvents,
    defineCustomElement: defineIcPageHeader
});

type IcPaginationEvents = { onIcPageChange: EventName<IcPaginationCustomEvent<IcChangeEventDetail>> };

export const IcPagination = /*@__PURE__*/ createComponent<IcPaginationElement, IcPaginationEvents>({
    tagName: 'ic-pagination',
    elementClass: IcPaginationElement,
    react: React,
    events: { onIcPageChange: 'icPageChange' } as IcPaginationEvents,
    defineCustomElement: defineIcPagination
});

type IcPaginationBarEvents = {
    onIcPageChange: EventName<IcPaginationBarCustomEvent<IcPageChangeEventDetail>>,
    onIcItemsPerPageChange: EventName<IcPaginationBarCustomEvent<IcItemsPerPageChangeEventDetail>>
};

export const IcPaginationBar = /*@__PURE__*/ createComponent<IcPaginationBarElement, IcPaginationBarEvents>({
    tagName: 'ic-pagination-bar',
    elementClass: IcPaginationBarElement,
    react: React,
    events: {
        onIcPageChange: 'icPageChange',
        onIcItemsPerPageChange: 'icItemsPerPageChange'
    } as IcPaginationBarEvents,
    defineCustomElement: defineIcPaginationBar
});

type IcPaginationItemEvents = NonNullable<unknown>;

export const IcPaginationItem = /*@__PURE__*/ createComponent<IcPaginationItemElement, IcPaginationItemEvents>({
    tagName: 'ic-pagination-item',
    elementClass: IcPaginationItemElement,
    react: React,
    events: {} as IcPaginationItemEvents,
    defineCustomElement: defineIcPaginationItem
});

type IcPopoverMenuEvents = { onIcPopoverClosed: EventName<IcPopoverMenuCustomEvent<HTMLIcMenuItemElement>> };

export const IcPopoverMenu = /*@__PURE__*/ createComponent<IcPopoverMenuElement, IcPopoverMenuEvents>({
    tagName: 'ic-popover-menu',
    elementClass: IcPopoverMenuElement,
    react: React,
    events: { onIcPopoverClosed: 'icPopoverClosed' } as IcPopoverMenuEvents,
    defineCustomElement: defineIcPopoverMenu
});

type IcRadioGroupEvents = { onIcChange: EventName<IcRadioGroupCustomEvent<IcChangeEventDetail>> };

export const IcRadioGroup = /*@__PURE__*/ createComponent<IcRadioGroupElement, IcRadioGroupEvents>({
    tagName: 'ic-radio-group',
    elementClass: IcRadioGroupElement,
    react: React,
    events: { onIcChange: 'icChange' } as IcRadioGroupEvents,
    defineCustomElement: defineIcRadioGroup
});

type IcRadioOptionEvents = {
    onIcCheck: EventName<IcRadioOptionCustomEvent<IcValueEventDetail>>,
    onIcSelectedChange: EventName<CustomEvent<void>>
};

export const IcRadioOption = /*@__PURE__*/ createComponent<IcRadioOptionElement, IcRadioOptionEvents>({
    tagName: 'ic-radio-option',
    elementClass: IcRadioOptionElement,
    react: React,
    events: {
        onIcCheck: 'icCheck',
        onIcSelectedChange: 'icSelectedChange'
    } as IcRadioOptionEvents,
    defineCustomElement: defineIcRadioOption
});

type IcSearchBarEvents = {
    onIcChange: EventName<IcSearchBarCustomEvent<IcValueEventDetail>>,
    onIcClear: EventName<CustomEvent<void>>,
    onIcInput: EventName<IcSearchBarCustomEvent<IcValueEventDetail>>,
    onIcOptionSelect: EventName<IcSearchBarCustomEvent<IcOptionSelectEventDetail>>,
    onIcMenuChange: EventName<IcSearchBarCustomEvent<IcMenuChangeEventDetail>>,
    onIcRetryLoad: EventName<IcSearchBarCustomEvent<IcMultiValueEventDetail>>,
    onIcSubmitSearch: EventName<IcSearchBarCustomEvent<IcValueEventDetail>>,
    onIcSearchBarBlur: EventName<IcSearchBarCustomEvent<IcSearchBarBlurEventDetail>>,
    onIcSearchBarFocus: EventName<IcSearchBarCustomEvent<IcValueEventDetail>>,
    onIcKeydown: EventName<IcSearchBarCustomEvent<{ event: KeyboardEvent }>>
};

export const IcSearchBar = /*@__PURE__*/ createComponent<IcSearchBarElement, IcSearchBarEvents>({
    tagName: 'ic-search-bar',
    elementClass: IcSearchBarElement,
    react: React,
    events: {
        onIcChange: 'icChange',
        onIcClear: 'icClear',
        onIcInput: 'icInput',
        onIcOptionSelect: 'icOptionSelect',
        onIcMenuChange: 'icMenuChange',
        onIcRetryLoad: 'icRetryLoad',
        onIcSubmitSearch: 'icSubmitSearch',
        onIcSearchBarBlur: 'icSearchBarBlur',
        onIcSearchBarFocus: 'icSearchBarFocus',
        onIcKeydown: 'icKeydown'
    } as IcSearchBarEvents,
    defineCustomElement: defineIcSearchBar
});

type IcSectionContainerEvents = NonNullable<unknown>;

export const IcSectionContainer = /*@__PURE__*/ createComponent<IcSectionContainerElement, IcSectionContainerEvents>({
    tagName: 'ic-section-container',
    elementClass: IcSectionContainerElement,
    react: React,
    events: {} as IcSectionContainerEvents,
    defineCustomElement: defineIcSectionContainer
});

type IcSelectEvents = {
    onIcBlur: EventName<CustomEvent<void>>,
    onIcChange: EventName<IcSelectCustomEvent<IcMultiValueEventDetail>>,
    onIcClear: EventName<CustomEvent<void>>,
    onIcClose: EventName<CustomEvent<void>>,
    onIcFocus: EventName<CustomEvent<void>>,
    onIcInput: EventName<IcSelectCustomEvent<IcMultiValueEventDetail>>,
    onIcOpen: EventName<CustomEvent<void>>,
    onIcOptionSelect: EventName<IcSelectCustomEvent<IcOptionSelectEventDetail>>,
    onIcOptionDeselect: EventName<IcSelectCustomEvent<IcOptionSelectEventDetail>>,
    onIcRetryLoad: EventName<IcSelectCustomEvent<IcMultiValueEventDetail>>
};

export const IcSelect = /*@__PURE__*/ createComponent<IcSelectElement, IcSelectEvents>({
    tagName: 'ic-select',
    elementClass: IcSelectElement,
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcChange: 'icChange',
        onIcClear: 'icClear',
        onIcClose: 'icClose',
        onIcFocus: 'icFocus',
        onIcInput: 'icInput',
        onIcOpen: 'icOpen',
        onIcOptionSelect: 'icOptionSelect',
        onIcOptionDeselect: 'icOptionDeselect',
        onIcRetryLoad: 'icRetryLoad'
    } as IcSelectEvents,
    defineCustomElement: defineIcSelect
});

type IcSideNavigationEvents = { onIcSideNavExpanded: EventName<IcSideNavigationCustomEvent<IcExpandedDetail>> };

export const IcSideNavigation = /*@__PURE__*/ createComponent<IcSideNavigationElement, IcSideNavigationEvents>({
    tagName: 'ic-side-navigation',
    elementClass: IcSideNavigationElement,
    react: React,
    events: { onIcSideNavExpanded: 'icSideNavExpanded' } as IcSideNavigationEvents,
    defineCustomElement: defineIcSideNavigation
});

type IcSkeletonEvents = NonNullable<unknown>;

export const IcSkeleton = /*@__PURE__*/ createComponent<IcSkeletonElement, IcSkeletonEvents>({
    tagName: 'ic-skeleton',
    elementClass: IcSkeletonElement,
    react: React,
    events: {} as IcSkeletonEvents,
    defineCustomElement: defineIcSkeleton
});

type IcSkipLinkEvents = NonNullable<unknown>;

export const IcSkipLink = /*@__PURE__*/ createComponent<IcSkipLinkElement, IcSkipLinkEvents>({
    tagName: 'ic-skip-link',
    elementClass: IcSkipLinkElement,
    react: React,
    events: {} as IcSkipLinkEvents,
    defineCustomElement: defineIcSkipLink
});

type IcStatusTagEvents = NonNullable<unknown>;

export const IcStatusTag = /*@__PURE__*/ createComponent<IcStatusTagElement, IcStatusTagEvents>({
    tagName: 'ic-status-tag',
    elementClass: IcStatusTagElement,
    react: React,
    events: {} as IcStatusTagEvents,
    defineCustomElement: defineIcStatusTag
});

type IcStepEvents = NonNullable<unknown>;

export const IcStep = /*@__PURE__*/ createComponent<IcStepElement, IcStepEvents>({
    tagName: 'ic-step',
    elementClass: IcStepElement,
    react: React,
    events: {} as IcStepEvents,
    defineCustomElement: defineIcStep
});

type IcStepperEvents = NonNullable<unknown>;

export const IcStepper = /*@__PURE__*/ createComponent<IcStepperElement, IcStepperEvents>({
    tagName: 'ic-stepper',
    elementClass: IcStepperElement,
    react: React,
    events: {} as IcStepperEvents,
    defineCustomElement: defineIcStepper
});

type IcSwitchEvents = {
    onIcBlur: EventName<CustomEvent<void>>,
    onIcChange: EventName<IcSwitchCustomEvent<IcSwitchChangeEventDetail>>,
    onIcFocus: EventName<CustomEvent<void>>
};

export const IcSwitch = /*@__PURE__*/ createComponent<IcSwitchElement, IcSwitchEvents>({
    tagName: 'ic-switch',
    elementClass: IcSwitchElement,
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcChange: 'icChange',
        onIcFocus: 'icFocus'
    } as IcSwitchEvents,
    defineCustomElement: defineIcSwitch
});

type IcTabEvents = NonNullable<unknown>;

export const IcTab = /*@__PURE__*/ createComponent<IcTabElement, IcTabEvents>({
    tagName: 'ic-tab',
    elementClass: IcTabElement,
    react: React,
    events: {} as IcTabEvents,
    defineCustomElement: defineIcTab
});

type IcTabContextEvents = { onIcTabSelect: EventName<IcTabContextCustomEvent<IcTabSelectEventDetail>> };

export const IcTabContext = /*@__PURE__*/ createComponent<IcTabContextElement, IcTabContextEvents>({
    tagName: 'ic-tab-context',
    elementClass: IcTabContextElement,
    react: React,
    events: { onIcTabSelect: 'icTabSelect' } as IcTabContextEvents,
    defineCustomElement: defineIcTabContext
});

type IcTabGroupEvents = NonNullable<unknown>;

export const IcTabGroup = /*@__PURE__*/ createComponent<IcTabGroupElement, IcTabGroupEvents>({
    tagName: 'ic-tab-group',
    elementClass: IcTabGroupElement,
    react: React,
    events: {} as IcTabGroupEvents,
    defineCustomElement: defineIcTabGroup
});

type IcTabPanelEvents = NonNullable<unknown>;

export const IcTabPanel = /*@__PURE__*/ createComponent<IcTabPanelElement, IcTabPanelEvents>({
    tagName: 'ic-tab-panel',
    elementClass: IcTabPanelElement,
    react: React,
    events: {} as IcTabPanelEvents,
    defineCustomElement: defineIcTabPanel
});

type IcTextFieldEvents = {
    onIcBlur: EventName<IcTextFieldCustomEvent<IcValueEventDetail>>,
    onIcChange: EventName<IcTextFieldCustomEvent<IcValueEventDetail>>,
    onIcFocus: EventName<IcTextFieldCustomEvent<IcValueEventDetail>>,
    onIcInput: EventName<IcTextFieldCustomEvent<IcValueEventDetail>>,
    onIcKeydown: EventName<IcTextFieldCustomEvent<IcTextFieldKeydownEventDetail>>,
    onIcScroll: EventName<CustomEvent<any>>
};

export const IcTextField = /*@__PURE__*/ createComponent<IcTextFieldElement, IcTextFieldEvents>({
    tagName: 'ic-text-field',
    elementClass: IcTextFieldElement,
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcChange: 'icChange',
        onIcFocus: 'icFocus',
        onIcInput: 'icInput',
        onIcKeydown: 'icKeydown',
        onIcScroll: 'icScroll'
    } as IcTextFieldEvents,
    defineCustomElement: defineIcTextField
});

type IcThemeEvents = { onIcThemeChange: EventName<IcThemeCustomEvent<IcThemeSettings>> };

export const IcTheme = /*@__PURE__*/ createComponent<IcThemeElement, IcThemeEvents>({
    tagName: 'ic-theme',
    elementClass: IcThemeElement,
    react: React,
    events: { onIcThemeChange: 'icThemeChange' } as IcThemeEvents,
    defineCustomElement: defineIcTheme
});

type IcToastEvents = { onIcDismiss: EventName<CustomEvent<void>> };

export const IcToast = /*@__PURE__*/ createComponent<IcToastElement, IcToastEvents>({
    tagName: 'ic-toast',
    elementClass: IcToastElement,
    react: React,
    events: { onIcDismiss: 'icDismiss' } as IcToastEvents,
    defineCustomElement: defineIcToast
});

type IcToastRegionEvents = NonNullable<unknown>;

export const IcToastRegion = /*@__PURE__*/ createComponent<IcToastRegionElement, IcToastRegionEvents>({
    tagName: 'ic-toast-region',
    elementClass: IcToastRegionElement,
    react: React,
    events: {} as IcToastRegionEvents,
    defineCustomElement: defineIcToastRegion
});

type IcToggleButtonEvents = {
    onIcToggleChecked: EventName<CustomEvent<{
        checked: boolean;
    }>>
};

export const IcToggleButton = /*@__PURE__*/ createComponent<IcToggleButtonElement, IcToggleButtonEvents>({
    tagName: 'ic-toggle-button',
    elementClass: IcToggleButtonElement,
    react: React,
    events: { onIcToggleChecked: 'icToggleChecked' } as IcToggleButtonEvents,
    defineCustomElement: defineIcToggleButton
});

type IcToggleButtonGroupEvents = { onIcChange: EventName<IcToggleButtonGroupCustomEvent<IcChangeEventDetail>> };

export const IcToggleButtonGroup = /*@__PURE__*/ createComponent<IcToggleButtonGroupElement, IcToggleButtonGroupEvents>({
    tagName: 'ic-toggle-button-group',
    elementClass: IcToggleButtonGroupElement,
    react: React,
    events: { onIcChange: 'icChange' } as IcToggleButtonGroupEvents,
    defineCustomElement: defineIcToggleButtonGroup
});

type IcTooltipEvents = { onIcTooltipShow: EventName<CustomEvent<void>> };

export const IcTooltip = /*@__PURE__*/ createComponent<IcTooltipElement, IcTooltipEvents>({
    tagName: 'ic-tooltip',
    elementClass: IcTooltipElement,
    react: React,
    events: { onIcTooltipShow: 'icTooltipShow' } as IcTooltipEvents,
    defineCustomElement: defineIcTooltip
});

type IcTopNavigationEvents = { onIcTopNavResized: EventName<CustomEvent<{ size: number }>> };

export const IcTopNavigation = /*@__PURE__*/ createComponent<IcTopNavigationElement, IcTopNavigationEvents>({
    tagName: 'ic-top-navigation',
    elementClass: IcTopNavigationElement,
    react: React,
    events: { onIcTopNavResized: 'icTopNavResized' } as IcTopNavigationEvents,
    defineCustomElement: defineIcTopNavigation
});

type IcTypographyEvents = NonNullable<unknown>;

export const IcTypography = /*@__PURE__*/ createComponent<IcTypographyElement, IcTypographyEvents>({
    tagName: 'ic-typography',
    elementClass: IcTypographyElement,
    react: React,
    events: {} as IcTypographyEvents,
    defineCustomElement: defineIcTypography
});
