'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type IcCalendarCustomEvent, type IcDataTableCustomEvent, type IcDataTableDataType, type IcDataTableTitleBarCustomEvent, type IcDateInputCustomEvent, type IcDatePickerCustomEvent, type IcDensityUpdateEventDetail, type IcDrawerCustomEvent, type IcDrawerExpandedDetail, type IcSortEventDetail, type IcTimeInputCustomEvent, type IcTimePeriods, type IcTimeSelectorCustomEvent, type IcTreeItemCustomEvent } from "@ukic/canary-web-components";
import type { Components } from "@ukic/canary-web-components/dist/components";
import { IcCalendar as IcCalendarElement, defineCustomElement as defineIcCalendar } from "@ukic/canary-web-components/dist/components/ic-calendar.js";
import { IcDataTableTitleBar as IcDataTableTitleBarElement, defineCustomElement as defineIcDataTableTitleBar } from "@ukic/canary-web-components/dist/components/ic-data-table-title-bar.js";
import { IcDataTable as IcDataTableElement, defineCustomElement as defineIcDataTable } from "@ukic/canary-web-components/dist/components/ic-data-table.js";
import { IcDateInput as IcDateInputElement, defineCustomElement as defineIcDateInput } from "@ukic/canary-web-components/dist/components/ic-date-input.js";
import { IcDatePicker as IcDatePickerElement, defineCustomElement as defineIcDatePicker } from "@ukic/canary-web-components/dist/components/ic-date-picker.js";
import { IcDrawer as IcDrawerElement, defineCustomElement as defineIcDrawer } from "@ukic/canary-web-components/dist/components/ic-drawer.js";
import { IcTableOfContents as IcTableOfContentsElement, defineCustomElement as defineIcTableOfContents } from "@ukic/canary-web-components/dist/components/ic-table-of-contents.js";
import { IcTimeInput as IcTimeInputElement, defineCustomElement as defineIcTimeInput } from "@ukic/canary-web-components/dist/components/ic-time-input.js";
import { IcTimeSelector as IcTimeSelectorElement, defineCustomElement as defineIcTimeSelector } from "@ukic/canary-web-components/dist/components/ic-time-selector.js";
import { IcTreeItem as IcTreeItemElement, defineCustomElement as defineIcTreeItem } from "@ukic/canary-web-components/dist/components/ic-tree-item.js";
import { IcTreeView as IcTreeViewElement, defineCustomElement as defineIcTreeView } from "@ukic/canary-web-components/dist/components/ic-tree-view.js";

export type IcCalendarEvents = {
    onIcChange: EventName<IcCalendarCustomEvent<{ value: Date | null; dateObject: { day: string | null; month: string | null; year: string | null; }; utcValue: Date | null; }>>,
    onIcCalendarClearButtonClick: EventName<IcCalendarCustomEvent<void>>,
    onIcCalendarMonthSelect: EventName<IcCalendarCustomEvent<void>>,
    onIcCalendarYearSelect: EventName<IcCalendarCustomEvent<void>>
};

export const IcCalendar: StencilReactComponent<IcCalendarElement, IcCalendarEvents, Components.IcCalendar> = /*@__PURE__*/ createComponent<IcCalendarElement, IcCalendarEvents, Components.IcCalendar>({
    tagName: 'ic-calendar',
    elementClass: IcCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIcChange: 'icChange',
        onIcCalendarClearButtonClick: 'icCalendarClearButtonClick',
        onIcCalendarMonthSelect: 'icCalendarMonthSelect',
        onIcCalendarYearSelect: 'icCalendarYearSelect'
    } as IcCalendarEvents,
    defineCustomElement: defineIcCalendar
});

export type IcDataTableEvents = {
    onIcRowHeightChange: EventName<IcDataTableCustomEvent<void>>,
    onIcSelectAllRows: EventName<IcDataTableCustomEvent<IcDataTableDataType[]>>,
    onIcSelectedRowChange: EventName<IcDataTableCustomEvent<{ row: IcDataTableDataType | null; selectedRows: IcDataTableDataType[]; icRowId: string | null; selectedIcRowIds: string[]; }>>,
    onIcColumnsLoaded: EventName<IcDataTableCustomEvent<void>>,
    onIcDataLoaded: EventName<IcDataTableCustomEvent<void>>,
    onIcSortChange: EventName<IcDataTableCustomEvent<IcSortEventDetail>>
};

export const IcDataTable: StencilReactComponent<IcDataTableElement, IcDataTableEvents, Components.IcDataTable> = /*@__PURE__*/ createComponent<IcDataTableElement, IcDataTableEvents, Components.IcDataTable>({
    tagName: 'ic-data-table',
    elementClass: IcDataTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIcRowHeightChange: 'icRowHeightChange',
        onIcSelectAllRows: 'icSelectAllRows',
        onIcSelectedRowChange: 'icSelectedRowChange',
        onIcColumnsLoaded: 'icColumnsLoaded',
        onIcDataLoaded: 'icDataLoaded',
        onIcSortChange: 'icSortChange'
    } as IcDataTableEvents,
    defineCustomElement: defineIcDataTable
});

export type IcDataTableTitleBarEvents = { onIcTableDensityUpdate: EventName<IcDataTableTitleBarCustomEvent<IcDensityUpdateEventDetail>> };

export const IcDataTableTitleBar: StencilReactComponent<IcDataTableTitleBarElement, IcDataTableTitleBarEvents, Components.IcDataTableTitleBar> = /*@__PURE__*/ createComponent<IcDataTableTitleBarElement, IcDataTableTitleBarEvents, Components.IcDataTableTitleBar>({
    tagName: 'ic-data-table-title-bar',
    elementClass: IcDataTableTitleBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onIcTableDensityUpdate: 'icTableDensityUpdate' } as IcDataTableTitleBarEvents,
    defineCustomElement: defineIcDataTableTitleBar
});

export type IcDateInputEvents = {
    onIcBlur: EventName<IcDateInputCustomEvent<{ value: Date | null }>>,
    onIcChange: EventName<IcDateInputCustomEvent<{ value: Date | null; dateObject: { day: string | null; month: string | null; year: string | null; }; utcValue: Date | null; }>>,
    onIcFocus: EventName<IcDateInputCustomEvent<{ value: Date | null }>>
};

export const IcDateInput: StencilReactComponent<IcDateInputElement, IcDateInputEvents, Components.IcDateInput> = /*@__PURE__*/ createComponent<IcDateInputElement, IcDateInputEvents, Components.IcDateInput>({
    tagName: 'ic-date-input',
    elementClass: IcDateInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcChange: 'icChange',
        onIcFocus: 'icFocus'
    } as IcDateInputEvents,
    defineCustomElement: defineIcDateInput
});

export type IcDatePickerEvents = { onIcChange: EventName<IcDatePickerCustomEvent<{ value: Date | null; dateObject?: { day: string | null; month: string | null; year: string | null; }; utcValue: Date | null; }>> };

export const IcDatePicker: StencilReactComponent<IcDatePickerElement, IcDatePickerEvents, Components.IcDatePicker> = /*@__PURE__*/ createComponent<IcDatePickerElement, IcDatePickerEvents, Components.IcDatePicker>({
    tagName: 'ic-date-picker',
    elementClass: IcDatePickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onIcChange: 'icChange' } as IcDatePickerEvents,
    defineCustomElement: defineIcDatePicker
});

export type IcDrawerEvents = { onIcDrawerExpanded: EventName<IcDrawerCustomEvent<IcDrawerExpandedDetail>> };

export const IcDrawer: StencilReactComponent<IcDrawerElement, IcDrawerEvents, Components.IcDrawer> = /*@__PURE__*/ createComponent<IcDrawerElement, IcDrawerEvents, Components.IcDrawer>({
    tagName: 'ic-drawer',
    elementClass: IcDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onIcDrawerExpanded: 'icDrawerExpanded' } as IcDrawerEvents,
    defineCustomElement: defineIcDrawer
});

export type IcTableOfContentsEvents = NonNullable<unknown>;

export const IcTableOfContents: StencilReactComponent<IcTableOfContentsElement, IcTableOfContentsEvents, Components.IcTableOfContents> = /*@__PURE__*/ createComponent<IcTableOfContentsElement, IcTableOfContentsEvents, Components.IcTableOfContents>({
    tagName: 'ic-table-of-contents',
    elementClass: IcTableOfContentsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcTableOfContentsEvents,
    defineCustomElement: defineIcTableOfContents
});

export type IcTimeInputEvents = {
    onIcBlur: EventName<IcTimeInputCustomEvent<{ value: Date | null }>>,
    onIcTimeChange: EventName<IcTimeInputCustomEvent<{ value: string | null; timeObject: { hour: string | null; minute: string | null; second: string | null; millisecond: string | null; period: string | null; }; }>>,
    onIcFocus: EventName<IcTimeInputCustomEvent<{ value: Date | null }>>
};

export const IcTimeInput: StencilReactComponent<IcTimeInputElement, IcTimeInputEvents, Components.IcTimeInput> = /*@__PURE__*/ createComponent<IcTimeInputElement, IcTimeInputEvents, Components.IcTimeInput>({
    tagName: 'ic-time-input',
    elementClass: IcTimeInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcTimeChange: 'icTimeChange',
        onIcFocus: 'icFocus'
    } as IcTimeInputEvents,
    defineCustomElement: defineIcTimeInput
});

export type IcTimeSelectorEvents = { onIcChange: EventName<IcTimeSelectorCustomEvent<{ value: Date | null; timeString: string | null; timeObject: { hour: string | null; minute: string | null; period?: IcTimePeriods; }; }>> };

export const IcTimeSelector: StencilReactComponent<IcTimeSelectorElement, IcTimeSelectorEvents, Components.IcTimeSelector> = /*@__PURE__*/ createComponent<IcTimeSelectorElement, IcTimeSelectorEvents, Components.IcTimeSelector>({
    tagName: 'ic-time-selector',
    elementClass: IcTimeSelectorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onIcChange: 'icChange' } as IcTimeSelectorEvents,
    defineCustomElement: defineIcTimeSelector
});

export type IcTreeItemEvents = {
    onIcTreeItemSelected: EventName<IcTreeItemCustomEvent<{ id: string }>>,
    onIcTreeItemExpanded: EventName<IcTreeItemCustomEvent<{ isExpanded: boolean; id: string; }>>
};

export const IcTreeItem: StencilReactComponent<IcTreeItemElement, IcTreeItemEvents, Components.IcTreeItem> = /*@__PURE__*/ createComponent<IcTreeItemElement, IcTreeItemEvents, Components.IcTreeItem>({
    tagName: 'ic-tree-item',
    elementClass: IcTreeItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onIcTreeItemSelected: 'icTreeItemSelected',
        onIcTreeItemExpanded: 'icTreeItemExpanded'
    } as IcTreeItemEvents,
    defineCustomElement: defineIcTreeItem
});

export type IcTreeViewEvents = NonNullable<unknown>;

export const IcTreeView: StencilReactComponent<IcTreeViewElement, IcTreeViewEvents, Components.IcTreeView> = /*@__PURE__*/ createComponent<IcTreeViewElement, IcTreeViewEvents, Components.IcTreeView>({
    tagName: 'ic-tree-view',
    elementClass: IcTreeViewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as IcTreeViewEvents,
    defineCustomElement: defineIcTreeView
});
