/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { type IcCalendarCustomEvent, type IcDataTableCustomEvent, type IcDataTableDataType, type IcDataTableTitleBarCustomEvent, type IcDateInputCustomEvent, type IcDatePickerCustomEvent, type IcDensityUpdateEventDetail, type IcDrawerCustomEvent, type IcDrawerExpandedDetail, type IcSortEventDetail, type IcTimeInputCustomEvent, type IcTimePeriods, type IcTimeSelectorCustomEvent } from "@ukic/canary-web-components";
import { IcCalendar as IcCalendarElement, defineCustomElement as defineIcCalendar } from "@ukic/canary-web-components/dist/components/ic-calendar.js";
import { IcDataTableTitleBar as IcDataTableTitleBarElement, defineCustomElement as defineIcDataTableTitleBar } from "@ukic/canary-web-components/dist/components/ic-data-table-title-bar.js";
import { IcDataTable as IcDataTableElement, defineCustomElement as defineIcDataTable } from "@ukic/canary-web-components/dist/components/ic-data-table.js";
import { IcDateInput as IcDateInputElement, defineCustomElement as defineIcDateInput } from "@ukic/canary-web-components/dist/components/ic-date-input.js";
import { IcDatePicker as IcDatePickerElement, defineCustomElement as defineIcDatePicker } from "@ukic/canary-web-components/dist/components/ic-date-picker.js";
import { IcDrawer as IcDrawerElement, defineCustomElement as defineIcDrawer } from "@ukic/canary-web-components/dist/components/ic-drawer.js";
import { IcTableOfContents as IcTableOfContentsElement, defineCustomElement as defineIcTableOfContents } from "@ukic/canary-web-components/dist/components/ic-table-of-contents.js";
import { IcTimeInput as IcTimeInputElement, defineCustomElement as defineIcTimeInput } from "@ukic/canary-web-components/dist/components/ic-time-input.js";
import { IcTimeSelector as IcTimeSelectorElement, defineCustomElement as defineIcTimeSelector } from "@ukic/canary-web-components/dist/components/ic-time-selector.js";
import { IcTreeItem as IcTreeItemElement, defineCustomElement as defineIcTreeItem } from "@ukic/canary-web-components/dist/components/ic-tree-item.js";
import { IcTreeView as IcTreeViewElement, defineCustomElement as defineIcTreeView } from "@ukic/canary-web-components/dist/components/ic-tree-view.js";
import React from 'react';

type IcCalendarEvents = {
    onIcChange: EventName<IcCalendarCustomEvent<{
        value: Date | null;
        dateObject: {
            day: string | null;
            month: string | null;
            year: string | null;
        };
        utcValue: Date | null;
    }>>,
    onIcCalendarClearButtonClick: EventName<CustomEvent<void>>,
    onIcCalendarMonthSelect: EventName<CustomEvent<void>>,
    onIcCalendarYearSelect: EventName<CustomEvent<void>>
};

export const IcCalendar = /*@__PURE__*/ createComponent<IcCalendarElement, IcCalendarEvents>({
    tagName: 'ic-calendar',
    elementClass: IcCalendarElement,
    react: React,
    events: {
        onIcChange: 'icChange',
        onIcCalendarClearButtonClick: 'icCalendarClearButtonClick',
        onIcCalendarMonthSelect: 'icCalendarMonthSelect',
        onIcCalendarYearSelect: 'icCalendarYearSelect'
    } as IcCalendarEvents,
    defineCustomElement: defineIcCalendar
});

type IcDataTableEvents = {
    onIcRowHeightChange: EventName<CustomEvent<void>>,
    onIcSelectAllRows: EventName<IcDataTableCustomEvent<IcDataTableDataType[]>>,
    onIcSelectedRowChange: EventName<IcDataTableCustomEvent<{
        row: IcDataTableDataType | null;
        selectedRows: IcDataTableDataType[];
        icRowId: string | null;
        selectedIcRowIds: string[];
    }>>,
    onIcColumnsLoaded: EventName<CustomEvent<void>>,
    onIcDataLoaded: EventName<CustomEvent<void>>,
    onIcSortChange: EventName<IcDataTableCustomEvent<IcSortEventDetail>>
};

export const IcDataTable = /*@__PURE__*/ createComponent<IcDataTableElement, IcDataTableEvents>({
    tagName: 'ic-data-table',
    elementClass: IcDataTableElement,
    react: React,
    events: {
        onIcRowHeightChange: 'icRowHeightChange',
        onIcSelectAllRows: 'icSelectAllRows',
        onIcSelectedRowChange: 'icSelectedRowChange',
        onIcColumnsLoaded: 'icColumnsLoaded',
        onIcDataLoaded: 'icDataLoaded',
        onIcSortChange: 'icSortChange'
    } as IcDataTableEvents,
    defineCustomElement: defineIcDataTable
});

type IcDataTableTitleBarEvents = { onIcTableDensityUpdate: EventName<IcDataTableTitleBarCustomEvent<IcDensityUpdateEventDetail>> };

export const IcDataTableTitleBar = /*@__PURE__*/ createComponent<IcDataTableTitleBarElement, IcDataTableTitleBarEvents>({
    tagName: 'ic-data-table-title-bar',
    elementClass: IcDataTableTitleBarElement,
    react: React,
    events: { onIcTableDensityUpdate: 'icTableDensityUpdate' } as IcDataTableTitleBarEvents,
    defineCustomElement: defineIcDataTableTitleBar
});

type IcDateInputEvents = {
    onIcBlur: EventName<IcDateInputCustomEvent<{ value: Date | null }>>,
    onIcChange: EventName<IcDateInputCustomEvent<{
        value: Date | null;
        dateObject: {
            day: string | null;
            month: string | null;
            year: string | null;
        };
        utcValue: Date | null;
    }>>,
    onIcFocus: EventName<IcDateInputCustomEvent<{ value: Date | null }>>
};

export const IcDateInput = /*@__PURE__*/ createComponent<IcDateInputElement, IcDateInputEvents>({
    tagName: 'ic-date-input',
    elementClass: IcDateInputElement,
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcChange: 'icChange',
        onIcFocus: 'icFocus'
    } as IcDateInputEvents,
    defineCustomElement: defineIcDateInput
});

type IcDatePickerEvents = {
    onIcChange: EventName<IcDatePickerCustomEvent<{
        value: Date | null;
        dateObject?: {
            day: string | null;
            month: string | null;
            year: string | null;
        };
        utcValue: Date | null;
    }>>
};

export const IcDatePicker = /*@__PURE__*/ createComponent<IcDatePickerElement, IcDatePickerEvents>({
    tagName: 'ic-date-picker',
    elementClass: IcDatePickerElement,
    react: React,
    events: { onIcChange: 'icChange' } as IcDatePickerEvents,
    defineCustomElement: defineIcDatePicker
});

type IcDrawerEvents = { onIcDrawerExpanded: EventName<IcDrawerCustomEvent<IcDrawerExpandedDetail>> };

export const IcDrawer = /*@__PURE__*/ createComponent<IcDrawerElement, IcDrawerEvents>({
    tagName: 'ic-drawer',
    elementClass: IcDrawerElement,
    react: React,
    events: { onIcDrawerExpanded: 'icDrawerExpanded' } as IcDrawerEvents,
    defineCustomElement: defineIcDrawer
});

type IcTableOfContentsEvents = NonNullable<unknown>;

export const IcTableOfContents = /*@__PURE__*/ createComponent<IcTableOfContentsElement, IcTableOfContentsEvents>({
    tagName: 'ic-table-of-contents',
    elementClass: IcTableOfContentsElement,
    react: React,
    events: {} as IcTableOfContentsEvents,
    defineCustomElement: defineIcTableOfContents
});

type IcTimeInputEvents = {
    onIcBlur: EventName<IcTimeInputCustomEvent<{ value: Date | null }>>,
    onIcTimeChange: EventName<CustomEvent<{
        value: string | null;
        timeObject: {
            hour: string | null;
            minute: string | null;
            second: string | null;
            millisecond: string | null;
            period: string | null;
        };
    }>>,
    onIcFocus: EventName<IcTimeInputCustomEvent<{ value: Date | null }>>
};

export const IcTimeInput = /*@__PURE__*/ createComponent<IcTimeInputElement, IcTimeInputEvents>({
    tagName: 'ic-time-input',
    elementClass: IcTimeInputElement,
    react: React,
    events: {
        onIcBlur: 'icBlur',
        onIcTimeChange: 'icTimeChange',
        onIcFocus: 'icFocus'
    } as IcTimeInputEvents,
    defineCustomElement: defineIcTimeInput
});

type IcTimeSelectorEvents = {
    onIcChange: EventName<IcTimeSelectorCustomEvent<{
        value: Date | null;
        timeString: string | null;
        timeObject: {
            hour: string | null;
            minute: string | null;
            period?: IcTimePeriods;
        };
    }>>
};

export const IcTimeSelector = /*@__PURE__*/ createComponent<IcTimeSelectorElement, IcTimeSelectorEvents>({
    tagName: 'ic-time-selector',
    elementClass: IcTimeSelectorElement,
    react: React,
    events: { onIcChange: 'icChange' } as IcTimeSelectorEvents,
    defineCustomElement: defineIcTimeSelector
});

type IcTreeItemEvents = {
    onIcTreeItemSelected: EventName<CustomEvent<{ id: string }>>,
    onIcTreeItemExpanded: EventName<CustomEvent<{
        isExpanded: boolean;
        id: string;
    }>>
};

export const IcTreeItem = /*@__PURE__*/ createComponent<IcTreeItemElement, IcTreeItemEvents>({
    tagName: 'ic-tree-item',
    elementClass: IcTreeItemElement,
    react: React,
    events: {
        onIcTreeItemSelected: 'icTreeItemSelected',
        onIcTreeItemExpanded: 'icTreeItemExpanded'
    } as IcTreeItemEvents,
    defineCustomElement: defineIcTreeItem
});

type IcTreeViewEvents = NonNullable<unknown>;

export const IcTreeView = /*@__PURE__*/ createComponent<IcTreeViewElement, IcTreeViewEvents>({
    tagName: 'ic-tree-view',
    elementClass: IcTreeViewElement,
    react: React,
    events: {} as IcTreeViewEvents,
    defineCustomElement: defineIcTreeView
});
