#!/bin/bash
bash "$(dirname "$0")/email-check.sh"

npm run test-cypress:headless

npm run lint:spelling

pwd=$(pwd)

cd packages/web-components
npm i --package-lock-only
cd /$pwd/packages/react
npm i --package-lock-only
cd /$pwd
npm run audit

npx lint-staged