#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run test-visual

pwd=$(pwd)

cd packages/web-components
npm i --package-lock-only
cd /$pwd/packages/react
npm i --package-lock-only
cd /$pwd
npm run audit

npx lint-staged