name: Canary Branches

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    paths:
      - /packages/canary-web-components/**
      - /packages/canary-react/**

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ic-ui-kit-static-analysis-tests:
    name: "Static Analysis Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps
          npm run build:all

      - name: Lint commit messages
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "$COMMIT_MESSAGE" | npx commitlint

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Audit
        run: npm run audit

      - name: A11y tests
        run: npm run test-a11y:ci

      - name: Unit Component tests
        run: npm run test:coverage-ci

  ic-ui-kit-e2e-tests:
    name: "E2E Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps

      - name: E2E tests
        run: npm run test-e2e

  ic-ui-kit-visual-tests:
    name: "Visual Regression Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: browser-actions/setup-chrome@latest
      - name: Install dependencies
        run: |
          google-chrome --version
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps

      - name: Visual Regression tests
        run: npm run test-visual:ci

  ic-ui-kit-deploy:
    needs:
      [
        ic-ui-kit-static-analysis-tests,
        ic-ui-kit-e2e-tests,
        ic-ui-kit-visual-tests,
      ]
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch' }}
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm run bootstrap -- -- --ci --legacy-peer-deps

      - name: Build components and web-components and react storybook
        run: |
          npm run build:canary
          npm run build-storybook:canary-web-components
          npm run build-storybook:canary-react

      - name: Deploy web components storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/canary-web-components/storybook-static
          target-folder: ./branches/${{ steps.extract_branch.outputs.branch }}/canary-web-components

      - name: Deploy react storybook
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./packages/canary-react/storybook-static
          target-folder: ./branches/${{ steps.extract_branch.outputs.branch }}/canary-react
